### ISSUE TITLE
grad_volume.py seg and img seems not correct

### ISSUE THREAD

**Issue by alphaccw** [ChenWWWeixiang/OpenCovidDetector#2]
Thanks for sharing the code.
- I notice that grad_volume.py, line 279, 280 img is reading from the path of mask, and seg is reading from the path of image, which would cause error for the next lines.
Could you check and correct it if I am right :)

**Comment by ChenWWWeixiang** [comment]
Thank you so much for telling us this issue. It is a BUG and we have tried to fix it in the newest commit.
