### ISSUE TITLE
Convert 2D slices to nii format after the segmentation step

### ISSUE THREAD

**Issue by hnguyentt** [ChenWWWeixiang/OpenCovidDetector#3]
In the document, you did the segmentation steps for 2D slices. How did you combine these 2D slices into `nii` files? Did you just stack 2D slices together?

**Comment by ChenWWWeixiang** [comment]
Yes, our segmentation was processed in slice level, and 3D segmentations were got by simply stacking all slices together.

**Comment by hnguyentt** [comment]
Thank you for your answer.
