### ISSUE TITLE
Grad-CAM for the final feature map

### ISSUE THREAD

**Issue by dlotfi** [ChenWWWeixiang/OpenCovidDetector#6]
Thank you for sharing your work

I noticed that you use the feature map of the second to last block in the ResNet152 model ("layer3" in torch implementation or "features/6" in your modified model) to create Grad-CAM (instead of the final feature map which is more common).
Could you please clarify this choice? It seems the output Grad-CAM of your code is somewhat noisy and does not highlight the important regions well.

**Comment by ChenWWWeixiang** [comment]
Thank you for your question. 
I have test the results of using the final feature map and found that the highlighted areas were much too coarse. Almost 1/3 of the lung were in high value of Grad-CAM if using the last feature map. To get better regions, we found that the noise can be reduce by erode and open operations.
